### login user
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "chenleo@sea.com",
  "password": "qwe@1234"
}


### sign up
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "chenleo@sea.com",
  "password": "qwe@1234",
  "confirmPassword": "qwe@1234"
}

### get user
GET http://localhost:8080/users/profile/5
Content-Type: application/json


### edit user
POST http://localhost:8080/users/edit/
Content-Type: application/json

{
  "nickname": "Leo",
  "birthday": "2025-02-12",
  "aboutMe": "Hi I'm Leo"
}